version: '3.7'

services:
  bot:
    build:
      context: .
      target: ${STAGE}
    image: pwsg_bot_bot:${STAGE}
    restart: on-failure
    stop_signal: SIGINT
    ports:
      - ${BOT_PORT}:80
    networks:
      - default
    depends_on:
      - db
      - redis
    env_file: .env

  db:
    image: postgres:13
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:6
    restart: on-failure
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - default
    volumes:
      - redis-data:/data
    env_file: .env

networks:
  default:

volumes:
  redis-data:
  postgres-data:
